name: Create cst-rakuten-backend image

on:
  push:
    branches:
      - main
jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Build and push image
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f ./infra/docker/Dockerfile.prod --tag ghcr.io/oondemand/cst-rakuten-backend:1.2.1 .
          docker push ghcr.io/oondemand/cst-rakuten-backend:1.2.1
