name: Login to kubectl

on:
  push:
    branches:
      - dev

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Create kubeconfig
        run: |
          mkdir -p "${HOME}/.kube"
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > "${HOME}/.kube/config"
          cat "${HOME}/.kube/config"

      - name: Use context
        run: |
          kubectl config use-context do-sfo2-oondemand-prod

      - name: Log configs
        run: |
          kubectl config get-contexts
