name: Teste yml

on:
  push:
    branches:
      - dev

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Permissão para o workflow criar tags

    steps:
      - uses: actions/checkout@v3

      - name: Teste deployment.yaml
        run: |
          ls

      - name: Substituir variáveis no deployment.yml
        run: |
          envsubst < infra/kubernetes/deployment.yaml

        env:
          IMAGE_TAG: 0.0.1
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          PORT: ${{ secrets.PORT }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_AUTH_SOURCE: ${{ secrets.DB_AUTH_SOURCE }}
          DB_REPLICA_SET: ${{ secrets.DB_REPLICA_SET }}
          DB_TSL: ${{ secrets.DB_TSL }}
          API_OMIE: ${{ secrets.API_OMIE }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENDGRID_REMETENTE: ${{ secrets.SENDGRID_REMETENTE }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          BASE_URL_CST: ${{ secrets.BASE_URL_CST }}
          BASE_URL_APP_PUBLISHER: ${{ secrets.BASE_URL_APP_PUBLISHER }}
          SCI_CODIGO_EMPRESA: ${{ secrets.SCI_CODIGO_EMPRESA }}
          SCI_CODIGO_CENTRO_CUSTO: ${{ secrets.SCI_CODIGO_CENTRO_CUSTO }}
          SCI_PORCENTAGEM_ISS: ${{ secrets.SCI_PORCENTAGEM_ISS }}
          SCI_DIAS_PAGAMENTO: ${{ secrets.SCI_DIAS_PAGAMENTO }}
          SCI_CBO: ${{ secrets.SCI_CBO }}
          SCI_CFIP: ${{ secrets.SCI_CFIP }}
          SCI_ESOCIAL: ${{ secrets.SCI_ESOCIAL }}
